events {}

http {
	keepalive_timeout 30;
	client_body_buffer_size 4096;
	client_header_buffer_size 1024;

	server {
		listen 127.0.0.1:8080;
		server_name cgi.lu;
		root /html2;

        location /
        {
            limit_except GET {
                deny all;
            }
        }
	}
}
