http {
	keepalive_timeout 30;
	client_body_buffer_size 1024;
	client_header_buffer_size 4096;
	root /general;
	
	server {
		listen 127.0.0.1:8080;
		listen 127.0.0.255:65535;
		server_name fabrice.42.fr zozo.42.fr;
		index index.php index.html;

		location / 
		{}
	}

	server {
		listen 127.0.0.1 4096;
		server_name Pasouk.42.fr;
		root /html2;
	}

	server {
		listen 127.0.0.1:65530;
		listen 65523 127.0.0.1;
		server_name toto.com;
		root /html3;

		location /image
		{
			root /html2/image;
		}
	}
}
