http {
	client_body_buffer_size 1024;
	server {
		listen 8080;
		listen 127.0.0.255:65535;
		server_name fabrice.42.fr zozo.42.fr;
		root /var/www/mysite;
		index index.php index.html;

		location / 
		{}
	}

	server {
		listen 127.0.0.1 4096;
		server_name Pasouk.42.fr;
		root /var/www/mysite2;
		client_body_buffer_size 2048;

		location /
		{
			root /var/www/loulousite
		}
	}

	server {
		listen 127.0.0.1:65530;
		listen 65523 127.0.0.1;
		server_name toto.com;
		root /var/www/sitetoto;
	}
}
