http {
	server {
		listen 8080;
		listen 0.0.0.0:65535;
		server_name fabrice.42.fr;
		root /var/www/mysite;
		index index.php index.html;

		location / 
		{}
	}
	server {
		listen 127.0.0.1 65530;
	}
}
