events {}

http {
	keepalive_timeout 12;
	client_body_buffer_size 65536;
	client_header_buffer_size 1024;
	client_body_temp_path ./Temp;
	client_max_body_size 4096;
	error_page 404 ./html/custom_404.html;
	error_page 403 ./html/custom_403.html;
	error_page 500 ./html/custom_500.html;

	server {
		listen 127.0.0.1:8080;
		server_name alpha.local localhost 127.0.0.1;
		root ./html;
		index index.html;
		error_page 404 ./html/custom_404.html;

		location / {
			root ./html;
			index index.html;
			limit_except GET {
				deny all;
			}
		}

		location *.py {
			root ./html;
			cgi_pass /usr/bin/python3;
			limit_except GET POST {
				deny all;
			}
		}

		location /post_small {
			client_max_body_size 12;
			limit_except POST {
				deny all;
			}
		}

		location /post_big {
			client_max_body_size 2048;
			limit_except POST {
				deny all;
			}
		}

		location /upload {
			client_max_body_size 2048;
			limit_except POST {
				deny all;
			}
		}

		location /media/ {
			alias ./html2;
			index index.html;
			limit_except GET {
				deny all;
			}
		}

		location /uploads/ {
			alias ./uploads;
			autoindex on;
			limit_except GET DELETE {
				deny all;
			}
		}

		location /old/ {
			return 301 /;
		}

		location /directory/ {
			alias ./YoupiBanane;
			index youpi.bad_extension;
			limit_except GET {
				deny all;
			}
		}
	}

	server {
		listen 127.0.0.1:8080;
		server_name beta.local;
		root ./html2;
		index index.html;
		client_max_body_size 300;
		error_page 404 ./html/custom_404.html;
		error_page 403 ./html/custom_403.html;
		error_page 500 ./html/custom_500.html;

		location / {
			root ./html2;
			index index.html;
			limit_except GET {
				deny all;
			}
		}

		location /holydays/ {
			alias ./html3/images;
			index index.html;
			limit_except GET {
				deny all;
			}
		}

		location /post_body {
			client_max_body_size 24;
			limit_except POST {
				deny all;
			}
		}
	}

	server {
		listen 127.0.0.1:9090;
		server_name gamma.local;
		root ./html3;
		index index.html;
		error_page 404 ./html/custom_404.html;
		error_page 403 ./html/custom_403.html;
		error_page 500 ./html/custom_500.html;

		location / {
			root ./html3;
			index index.html;
			limit_except GET {
				deny all;
			}
		}

		location /images/ {
			alias ./html3/images;
			index index.html;
			limit_except GET {
				deny all;
			}
		}
	}
}
