http {
	client_max_body_size 4096;
	client_header_buffer_size 10000;
	keepalive_timeout 300;

	server {
		listen 127.0.0.1:8080;
		server_name fabrice.42.fr zozo.42.fr;
		root ./html;
		index index.html;

		location / {
			root ./html;
			limit_except GET HEAD DELETE {
			}
		}

		location /api/upload {
			root ./html;
			limit_except POST {
			}
		}

		location /post_body {
			root ./html;
			client_max_body_size 100;
			limit_except POST {
			}
		}

		location /*.bla {
			root ./;
			cgi_pass ./cgi_tester;
			limit_except POST {
				deny all;
			}
		}

		location /directory/ {
			alias ./YoupiBanane;
			index youpi.bad_extension;
			limit_except GET HEAD {
			}
		}
	}
}
