events {}

http {
	keepalive_timeout 12;
	client_body_buffer_size 10;
	client_header_buffer_size 7;

	server {
		listen 8080;
		server_name localhost;

		location /cgi-bin/*.bla {
			root /home/fabrice/Documents/webserv/;
			cgi_pass /home/fabrice/Documents/webserv/cgi_tester;
			limit_except POST { 
				deny all; 
			}
		}
	}

	server {
		listen 127.0.0.1:4098;
		location /cgi-bin/python/*.py {
			root ./;
			cgi_pass;
		}
	}

	server {
		listen 4096;
		server_name luLUlu.lu;
		root ./html;
	}

	server {
		listen 4096;
		server_name zozozo.zo;
		root ./html2;
		client_max_body_size 300;

		location /holydays/
		{
			alias ./html3/image;
			limit_except GET { 
				deny all; 
			}
			client_max_body_size 24;
		}
	}
}
