events {}

http {
	keepalive_timeout 12;
	client_body_buffer_size 2;
	client_header_buffer_size 2;

	server {
		listen 127.0.0.1:8080;
		server_name cgi.lu;
		root /html4;

		location /cgi-bin/
		{
			cgi_pass /cgi-bin/; 
		}
	}

	server {
		listen 127.0.0.1:4096;
		server_name luLUlu.lu;
		root /html;

		location /videos {
			
		}
	}

	server {
		listen 127.0.0.1:4096;
		server_name zozozo.zo;
		root /html2;
		client_max_body_size 300;

		location /holydays
		{
			root /html3/image;
			limit_except GET { 
				deny all; 
			}
			client_max_body_size 24;
		}
	}
}
