events {}

http {
	keepalive_timeout 12;
	client_body_buffer_size 8192;
	client_header_buffer_size 1024;
	client_body_temp_path ./Temp;
	client_max_body_size 4096;

	server {
		listen 127.0.0.1:8080;
		server_name fabrice.42.fr zozo.42.fr;

		location / {
			root ./html;
			limit_except GET {
				deny all;
			}
		}

		location /post_body {
			client_max_body_size 100;
			limit_except POST {
				deny all;
			}
		}

		location /*.bla {
			cgi_pass ./cgi_tester;
			limit_except POST { 
				deny all;
			}
		}

		location /directory/ {
			alias ./YoupiBanane;
			index youpi.bad_extension;

			limit_except GET {
				deny all;
			}
		}


	}
}
