events {}

http {
	keepalive_timeout 30;
	client_body_buffer_size 10;
	client_header_buffer_size 7;
	client_max_body_size 4096;
	
	server {
		listen 127.0.0.1:8080;
		server_name fabrice.42.fr zozo.42.fr;

		location / 
		{ }
	}

	server {
		listen 127.0.0.1:65530;
		listen 127.0.0.1:65523;
		server_name toto.com;
		root /html3;

		location /holydays
		{
			root /html3/image;
			limit_except GET { 
				deny all; 
			}
		}
	}	

	server {
		listen 127.0.0.1:4096;
		server_name luLUlu.lu;
		root /html;

		location /videos {
			
		}
	}

	server {
		listen 127.0.0.1:4096;
		server_name zozozo.zo;
		root /html2;
	}

	server {
		listen 127.0.0.1:4096;
		server_name luLUlu.lu;
		root /html;

		location /videos {
			alias /html/videos;
		}
	}

}
