events {}

http {
	keepalive_timeout 3;
	client_body_buffer_size 5;
	client_header_buffer_size 7;

	server {
		listen 8080;
		server_name localhost;
	
		location /cgi-bin/ {
			root ./;
			cgi_pass ./cgi_tester;
			limit_except POST { 
				deny all;
			}
		}

		location /cgi-bin/python/*.py {
			root ./;
			cgi_pass /usr/bin/python3;
			limit_except POST GET { 
				deny all;
			}
		}

		location / {
			alias ./;
			cgi_pass;
			limit_except POST { 
				deny all;
			}
		}

		location /directory/*.bla {
			alias ./YoupiBanane;
			cgi_pass ./cgi_tester;
			limit_except POST { 
				deny all;
			}
		}
	}

	server {
		listen 8080;
		server_name localhost;
		root ./htmpl2;
	}

	server {
		listen 4096;
		server_name luLUlu.lu;
		root ./html;
	}

	server {
		listen 4096;
		server_name zozozo.zo;
		root ./html2;
		client_max_body_size 300;

		location /holydays/
		{
			alias ./html3/image;
			limit_except GET { 
				deny all; 
			}
			client_max_body_size 24;
		}
	}
}
